export const berriesData = [
    {
      id: 1,
      src: require("../../assets/food/berries/watermelon.webp"),
      category: "Ягоды",
      russian: "арбуз",
      khadar: "харбуз",
      english: "watermelon",
      additional_info: "",
      sound_src: "apple.m4a",
    },
    {
      id: 2,
      src: require("../../assets/food/berries/cherry.webp"),
      category: "Ягоды",
      russian: "вишня",
      khadar: "жиъа",
      english: "cherry",
      additional_info: "",
      sound_src: "apricot.m4a",
    },
    {
      id: 3,
      src: require("../../assets/food/berries/pomegranate.webp"),
      category: "Ягоды",
      russian: "гранат",
      khadar: "нар",
      english: "pomegranate",
      additional_info: "",
      sound_src: "quince.m4a",
    },
    {
      id: 4,
      src: require("../../assets/food/berries/melon.webp"),
      category: "Ягоды",
      russian: "дыня",
      khadar: "пастан",
      english: "melon",
      additional_info: "",
      sound_src: "cherry_plum.m4a",
    },
    {
      id: 5,
      src: require("../../assets/food/berries/blackberry.webp"),
      category: "Ягоды",
      russian: "ежевика",
      khadar: "ирбиъа",
      english: "blackberry",
      additional_info: "",
      sound_src: "grape.m4a",
    },
    {
      id: 6,
      src: require("../../assets/food/berries/strawberry.webp"),
      category: "Ягоды",
      russian: "земляника",
      khadar: "гъалаъа",
      english: "strawberry",
      additional_info: "",
      sound_src: "pear.m4a",
    },
    {
      id: 7,
      src: require("../../assets/food/berries/dogwood.webp"),
      category: "Ягоды",
      russian: "кизил",
      khadar: "жугьам",
      english: "dogwood",
      additional_info: "",
      sound_src: "plum.m4a",
    },
    {
      id: 8,
      src: require("../../assets/food/berries/raspberry.webp"),
      category: "Ягоды",
      russian: "малина",
      khadar: "мамаргIя",
      english: "raspberry",
      additional_info: "",
      sound_src: "pumpkin.m4a",
    },
    {
        id: 8,
        src: require("../../assets/food/berries/mulberry.webp"),
        category: "Ягоды",
        russian: "тутовник",
        khadar: "тут",
        english: "mulberry",
        additional_info: "",
        sound_src: "pumpkin.m4a",
      },
      {
        id: 8,
        src: require("../../assets/food/berries/persimmon.webp"),
        category: "Ягоды",
        russian: "хурма",
        khadar: "гургуба",
        english: "persimmon",
        additional_info: "",
        sound_src: "pumpkin.m4a",
      },
      {
        id: 8,
        src: require("../../assets/food/berries/sweet_cherry.webp"),
        category: "Ягоды",
        russian: "черешня",
        khadar: "баъли",
        english: "sweet cherry",
        additional_info: "",
        sound_src: "pumpkin.m4a",
      },
      {
        id: 8,
        src: require("../../assets/food/berries/rosehip.webp"),
        category: "Ягоды",
        russian: "шиповник",
        khadar: "мизуха",
        english: "rosehip",
        additional_info: "",
        sound_src: "pumpkin.m4a",
      },
]