export const birdsData = [
    {
        id: 1,
        src: require("../../assets/birds/sparrow.png"),
        category: "Птицы",
        russian: "соловей",
        khadar: "тIавтIав",
        english: "sparrow",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 1,
        src: require("../../assets/birds/crow.png"),
        category: "Птицы",
        russian: "ворона",
        khadar: "гъана",
        english: "crow",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/birds/pigeon.png"),
        category: "Птицы",
        russian: "голубь",
        khadar: "лахьиъ",
        english: "pigeon",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/birds/goose.png"),
        category: "Птицы",
        russian: "гусь",
        khadar: "къаз",
        english: "goose",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/birds/woodpecker.png"),
        category: "Птицы",
        russian: "дятел",
        khadar: "къутIкъутIи",
        english: "woodpecker",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 6,
        src: require("../../assets/birds/turkey.png"),
        category: "Птицы",
        russian: "индюк",
        khadar: "гургур",
        english: "turkey",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 7,
        src: require("../../assets/birds/cuckoo.png"),
        category: "Птицы",
        russian: "кукушка",
        khadar: "утук",
        english: "cuckoo",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 8,
        src: require("../../assets/birds/swallow.png"),
        category: "Птицы",
        russian: "ласточка",
        khadar: "гъагатIи",
        english: "swallow",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 9,
        src: require("../../assets/birds/eagle.png"),
        category: "Птицы",
        russian: "орел",
        khadar: "гъуш",
        english: "eagle",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 10,
        src: require("../../assets/birds/peacock.png"),
        category: "Птицы",
        russian: "павлин",
        khadar: "тIавус",
        english: "peacock",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 11,
        src: require("../../assets/birds/rooster.png"),
        category: "Птицы",
        russian: "петух",
        khadar: "датхъа",
        english: "rooster",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 12,
        src: require("../../assets/birds/bird.png"),
        category: "Молочные продукты",
        russian: "птица",
        khadar: "чикIа",
        english: "bird",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 13,
        src: require("../../assets/birds/nightingale.png"),
        category: "Птицы",
        russian: "соловей",
        khadar: "булбул",
        english: "nightingale",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 14,
        src: require("../../assets/birds/magpie.png"),
        category: "Птицы",
        russian: "сорока",
        khadar: "кIамкIамаги",
        english: "magpie",
        additional_info: "",
        sound_src: "apple.m4a",
      },
]