export const birdsData = [
    {
        id: 1,
        src: require("../../assets/animals/birds/sparrow.webp"),
        category: "Птицы",
        russian: "воробей",
        khadar: "тIавтIав",
        english: "sparrow",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 1,
        src: require("../../assets/animals/birds/crow.webp"),
        category: "Птицы",
        russian: "ворона",
        khadar: "гъана",
        english: "crow",
        additional_info: "\"Гъана\" также имеет значение \"ложь\".",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/animals/birds/pigeon.webp"),
        category: "Птицы",
        russian: "голубь",
        khadar: "лахьиъ",
        english: "pigeon",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/animals/birds/goose.webp"),
        category: "Птицы",
        russian: "гусь",
        khadar: "къаз",
        english: "goose",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/animals/birds/woodpecker.webp"),
        category: "Птицы",
        russian: "дятел",
        khadar: "къутIкъутIи",
        english: "woodpecker",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 6,
        src: require("../../assets/animals/birds/turkey.webp"),
        category: "Птицы",
        russian: "индюк",
        khadar: "гургур",
        english: "turkey",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 7,
        src: require("../../assets/animals/birds/cuckoo.webp"),
        category: "Птицы",
        russian: "кукушка",
        khadar: "утук",
        english: "cuckoo",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 8,
        src: require("../../assets/animals/birds/swallow.webp"),
        category: "Птицы",
        russian: "ласточка",
        khadar: "гъагатIи",
        english: "swallow",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 9,
        src: require("../../assets/animals/birds/eagle.webp"),
        category: "Птицы",
        russian: "орел",
        khadar: "гъуш",
        english: "eagle",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 10,
        src: require("../../assets/animals/birds/peacock.webp"),
        category: "Птицы",
        russian: "павлин",
        khadar: "тIавус",
        english: "peacock",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 11,
        src: require("../../assets/animals/birds/rooster.webp"),
        category: "Птицы",
        russian: "петух",
        khadar: "дагъай",
        english: "rooster",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 12,
        src: require("../../assets/animals/birds/bird.webp"),
        category: "Молочные продукты",
        russian: "птица",
        khadar: "чикIа",
        english: "bird",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 13,
        src: require("../../assets/animals/birds/nightingale.webp"),
        category: "Птицы",
        russian: "соловей",
        khadar: "булбул",
        english: "nightingale",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 14,
        src: require("../../assets/animals/birds/magpie.webp"),
        category: "Птицы",
        russian: "сорока",
        khadar: "кIамкIамаги",
        english: "magpie",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 15,
        src: require("../../assets/animals/birds/owl.webp"),
        category: "Птицы",
        russian: "сова",
        khadar: "тIуми",
        english: "owl",
        additional_info: "",
        sound_src: "apple.m4a",
      },
]