export const bodyPartsData = [
    {
        id: 1,
        src: require("../../assets/body_parts/thigh.png"),
        category: "Части тела",
        russian: "бедро",
        khadar: "урдур",
        english: "thigh",
        additional_info: "Урдур обозначает бедро для людей, для животных бёдер используется слово \"чарда.\"",
        sound_src: "apple.m4a",
      },  
      {
        id: 2,
        src: require("../../assets/body_parts/beard.png"),
        category: "Части тела",
        russian: "борода",
        khadar: "муцIур",
        english: "beard",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 3,
        src: require("../../assets/body_parts/eyebrow.png"),
        category: "Части тела",
        russian: "бровь",
        khadar: "нед",
        english: "eyebrow",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 4,
        src: require("../../assets/body_parts/vein.png"),
        category: "Части тела",
        russian: "вена",
        khadar: "тамур",
        english: "vein",
        additional_info: "Так можно называть и артерию (artery).",
        sound_src: "apple.m4a",
      }, 
      {
        id: 5,
        src: require("../../assets/body_parts/hair.png"),
        category: "Части тела",
        russian: "волосы",
        khadar: "гъизбе",
        english: "hair",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 6,
        src: require("../../assets/body_parts/eye.png"),
        category: "Части тела",
        russian: "глаз",
        khadar: "хIули",
        english: "eye",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 7,
        src: require("../../assets/body_parts/shin.png"),
        category: "Части тела",
        russian: "голень",
        khadar: "кIинкI",
        english: "shin",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 8,
        src: require("../../assets/body_parts/head.png"),
        category: "Части тела",
        russian: "голова",
        khadar: "бекI",
        english: "head",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 9,
        src: require("../../assets/body_parts/throat.png"),
        category: "Части тела",
        russian: "горло / глотка",
        khadar: "сус",
        english: "throat",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 10,
        src: require("../../assets/body_parts/lip.png"),
        category: "Части тела",
        russian: "губа",
        khadar: "кIонтI",
        english: "lip",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 11,
        src: require("../../assets/body_parts/fecal.png"),
        category: "Части тела",
        russian: "дерьмо",
        khadar: "пухъ",
        english: "дерьмо",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 12,
        src: require("../../assets/body_parts/gum.png"),
        category: "Части тела",
        russian: "десна",
        khadar: "какур?",
        english: "gum",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 13,
        src: require("../../assets/body_parts/stomach.png"),
        category: "Части тела",
        russian: "желудок",
        khadar: "ашхазан",
        english: "stomach",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 14,
        src: require("../../assets/body_parts/bile.png"),
        category: "Части тела",
        russian: "желчь",
        khadar: "гьими",
        english: "bile",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 15,
        src: require("../../assets/body_parts/belly.png"),
        category: "Части тела",
        russian: "живот",
        khadar: "кони",
        english: "belly",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 
      {
        id: 16,
        src: require("../../assets/body_parts/fat.png"),
        category: "Части тела",
        russian: "жир",
        khadar: "хIале",
        english: "fat",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 17,
        src: require("../../assets/body_parts/nape.png"),
        category: "Части тела",
        russian: "затылок",
        khadar: "хъантIа",
        english: "nape",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 18,
        src: require("../../assets/body_parts/adam_apple.png"),
        category: "Части тела",
        russian: "кадык",
        khadar: "кирдан",
        english: "Adam's apple",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 19,
        src: require("../../assets/body_parts/bowel.png"),
        category: "Части тела",
        russian: "кишка",
        khadar: "ичак",
        english: "bowel",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 20,
        src: require("../../assets/body_parts/skin.png"),
        category: "Части тела",
        russian: "кожа",
        khadar: "кам",
        english: "skin",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 21,
        src: require("../../assets/body_parts/knee.png"),
        category: "Части тела",
        russian: "колено",
        khadar: "кIункъа",
        english: "knee",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 22,
        src: require("../../assets/body_parts/spinal_cord.png"),
        category: "Части тела",
        russian: "спинной мозг",
        khadar: "лигала мяхIа",
        english: "spinal cord",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 23,
        src: require("../../assets/body_parts/blood.png"),
        category: "Части тела",
        russian: "кровь",
        khadar: "хIи",
        english: "blood",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 24,
        src: require("../../assets/body_parts/tooth.png"),
        category: "Части тела",
        russian: "зуб",
        khadar: "цуа",
        english: "tooth",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 25,
        src: require("../../assets/body_parts/face.png"),
        category: "Части тела",
        russian: "лицо",
        khadar: "бахI",
        english: "face",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 26,
        src: require("../../assets/body_parts/forehead.png"),
        category: "Части тела",
        russian: "лоб",
        khadar: "анда",
        english: "forehead",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 27,
        src: require("../../assets/body_parts/elbow.png"),
        category: "Части тела",
        russian: "локоть",
        khadar: "газабилакъ",
        english: "elbow",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 28,
        src: require("../../assets/body_parts/brain.png"),
        category: "Части тела",
        russian: "мозг",
        khadar: "мяхIа",
        english: "brain",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 29,
        src: require("../../assets/body_parts/urine.png"),
        category: "Части тела",
        russian: "моча",
        khadar: "жяхI",
        english: "urine",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 30,
        src: require("../../assets/body_parts/bladder.png"),
        category: "Части тела",
        russian: "мочевой пузырь",
        khadar: "жяхIла коча",
        english: "bladder",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 31,
        src: require("../../assets/body_parts/palate.png"),
        category: "Части тела",
        russian: "нёбо",
        khadar: "къак",
        english: "palate",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 32,
        src: require("../../assets/body_parts/leg.png"),
        category: "Части тела",
        russian: "нога",
        khadar: "кьяш",
        english: "leg",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 33,
        src: require("../../assets/body_parts/nail.png"),
        category: "Части тела",
        russian: "ноготь",
        khadar: "нико",
        english: "nail",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 34,
        src: require("../../assets/body_parts/nostril.png"),
        category: "Части тела",
        russian: "ноздря",
        khadar: "тIели",
        english: "ноздря",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 35,
        src: require("../../assets/body_parts/sinus.png"),
        category: "Части тела",
        russian: "пазуха",
        khadar: "шанкIа",
        english: "sinus",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 36,
        src: require("../../assets/body_parts/finger.png"),
        category: "Части тела",
        russian: "палец",
        khadar: "тIул",
        english: "finger",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 37,
        src: require("../../assets/body_parts/liver.png"),
        category: "Части тела",
        russian: "печень",
        khadar: "дулек",
        english: "liver",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 38,
        src: require("../../assets/body_parts/armpit.png"),
        category: "Части тела",
        russian: "подмышка",
        khadar: "шанкIалаудиъ",
        english: "armpit",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 39,
        src: require("../../assets/body_parts/spine.png"),
        category: "Части тела",
        russian: "позвоночник",
        khadar: "гъакъла лига",
        english: "spine",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 40,
        src: require("../../assets/body_parts/sweat.png"),
        category: "Части тела",
        russian: "пот",
        khadar: "майъа",
        english: "sweat",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 41,
        src: require("../../assets/body_parts/forearm.png"),
        category: "Части тела",
        russian: "предплечье",
        khadar: "билакъ",
        english: "forearm",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 42,
        src: require("../../assets/body_parts/heel.png"),
        category: "Части тела",
        russian: "пятка",
        khadar: "къагIя",
        english: "heel",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 43,
        src: require("../../assets/body_parts/wound.png"),
        category: "Части тела",
        russian: "рана",
        khadar: "дахъи",
        english: "wound",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 44,
        src: require("../../assets/body_parts/rib.png"),
        category: "Части тела",
        russian: "ребро",
        khadar: "бургъун",
        english: "rib",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 45,
        src: require("../../assets/body_parts/eyelash.png"),
        category: "Части тела",
        russian: "ресница",
        khadar: "кирпик",
        english: "eyelash",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 46,
        src: require("../../assets/body_parts/arm.png"),
        category: "Части тела",
        russian: "рука",
        khadar: "някь",
        english: "arm",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 47,
        src: require("../../assets/body_parts/spleen.png"),
        category: "Части тела",
        russian: "селезень",
        khadar: "къацIа",
        english: "spleen",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 48,
        src: require("../../assets/body_parts/heart.png"),
        category: "Части тела",
        russian: "сердце",
        khadar: "уркIи",
        english: "heart",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 48,
        src: require("../../assets/body_parts/skeleton.png"),
        category: "Части тела",
        russian: "скелет",
        khadar: "искелет",
        english: "skeleton",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 49,
        src: require("../../assets/body_parts/tear.png"),
        category: "Части тела",
        russian: "слеза",
        khadar: "неръ",
        english: "tear",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 50,
        src: require("../../assets/body_parts/saliva.png"),
        category: "Части тела",
        russian: "слюна",
        khadar: "щаркие",
        english: "saliva",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 51,
        src: require("../../assets/body_parts/back.png"),
        category: "Части тела",
        russian: "спина",
        khadar: "гъакъ",
        english: "back",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 52,
        src: require("../../assets/body_parts/waist.png"),
        category: "Части тела",
        russian: "талия",
        khadar: "бай",
        english: "waist",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 53,
        src: require("../../assets/body_parts/ear.png"),
        category: "Части тела",
        russian: "ухо",
        khadar: "лихIи",
        english: "ear",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 54,
        src: require("../../assets/body_parts/jaw.png"),
        category: "Части тела",
        russian: "челюсть",
        khadar: "къайкъай",
        english: "jaw",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 55,
        src: require("../../assets/body_parts/neck.png"),
        category: "Части тела",
        russian: "шея",
        khadar: "къяб",
        english: "neck",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 56,
        src: require("../../assets/body_parts/cheek.png"),
        category: "Части тела",
        russian: "щека",
        khadar: "лажи",
        english: "cheek",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 57,
        src: require("../../assets/body_parts/buttock.png"),
        category: "Части тела",
        russian: "ягодица",
        khadar: "ирхъи",
        english: "buttock",
        additional_info: "",
        sound_src: "apple.m4a",
      }, 


]