export const crawlingData = [
    {
        id: 1,
        src: require("../../assets/animals/crawling/worm.webp"),
        category: "Ползучие",
        russian: "червь; глист",
        khadar: "мелякъ / шулерк",
        english: "worm",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 2,
        src: require("../../assets/animals/crawling/snake.webp"),
        category: "Ползучие",
        russian: "змея",
        khadar: "мусанабашан",
        english: "snake",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/animals/crawling/spider.webp"),
        category: "Ползучие",
        russian: "паук",
        khadar: "пайлигьан",
        english: "spider",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/animals/crawling/scorpion.webp"),
        category: "Ползучие",
        russian: "скорпион",
        khadar: "кьякьярав",
        english: "scorpion",
        additional_info: "",
        sound_src: "apple.m4a",
      },
]