export const crawlingData = [
    {
        id: 1,
        src: require("../../assets/crawling/worm.png"),
        category: "Ползучие",
        russian: "червь; глист",
        khadar: "мелякъ / шулерк",
        english: "worm",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 2,
        src: require("../../assets/crawling/snake.png"),
        category: "Ползучие",
        russian: "змея",
        khadar: "мусанабашан",
        english: "snake",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/crawling/spider.png"),
        category: "Ползучие",
        russian: "паук",
        khadar: "пайлигьан",
        english: "spider",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/crawling/scorpion.png"),
        category: "Ползучие",
        russian: "скорпион",
        khadar: "кьякьярав",
        english: "scorpion",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/crawling/rat.png"),
        category: "Ползучие",
        russian: "крыса",
        khadar: "къургугваца",
        english: "rat",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      
]