export const dairyData = [
    
    {
        id: 1,
        src: require("../../assets/food/dairy/kefir.webp"),
        category: "Молочные продукты",
        russian: "кефир",
        khadar: "беръне",
        english: "kefir",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 2,
        src: require("../../assets/food/dairy/milk.webp"),
        category: "Молочные продукты",
        russian: "молоко",
        khadar: "миъ",
        english: "milk",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/food/dairy/butter.webp"),
        category: "Молочные продукты",
        russian: "сливочное масло",
        khadar: "къама",
        english: "butter",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/food/dairy/sour_cream.webp"),
        category: "Молочные продукты",
        russian: "сметана",
        khadar: "гъайнакъ",
        english: "sour cream",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/food/dairy/cheese.webp"),
        category: "Молочные продукты",
        russian: "сыр",
        khadar: "нусаъ",
        english: "cheese",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 6,
        src: require("../../assets/food/dairy/ghee.webp"),
        category: "Молочные продукты",
        russian: "топленое масло",
        khadar: "рахсаг",
        english: "ghee",
        additional_info: "",
        sound_src: "apple.m4a",
      }
]