export const eventsData = [{
    id: 1,
    src: require("../../assets/nature/events/coast.webp"),
    category: "Явления / окружающая среда",
    russian: "берег",
    khadar: "дуб",
    english: "coast",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 2,
    src: require("../../assets/nature/events/wind.webp"),
    category: "Явления / окружающая среда",
    russian: "ветер",
    khadar: "букма",
    english: "wind",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 3,
    src: require("../../assets/nature/events/air.webp"),
    category: "Явления / окружающая среда",
    russian: "воздух",
    khadar: "гьава",
    english: "air",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 4,
    src: require("../../assets/nature/events/clay.webp"),
    category: "Явления / окружающая среда",
    russian: "глина",
    khadar: "гIянжи",
    english: "clay",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 5,
    src: require("../../assets/nature/events/mountain.webp"),
    category: "Явления / окружающая среда",
    russian: "гора",
    khadar: "дубура",
    english: "mountain",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 6,
    src: require("../../assets/nature/events/thunder.webp"),
    category: "Явления / окружающая среда",
    russian: "гром",
    khadar: "гъугъу",
    english: "thunder",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 7,
    src: require("../../assets/nature/events/lightning.webp"),
    category: "Явления / окружающая среда",
    russian: "молния",
    khadar: "ламцIи",
    english: "lightning",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 8,
    src: require("../../assets/nature/events/rain.webp"),
    category: "Явления / окружающая среда",
    russian: "дождь",
    khadar: "заб",
    english: "rain",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 9,
    src: require("../../assets/nature/events/hail.webp"),
    category: "Явления / окружающая среда",
    russian: "град",
    khadar: "къапкъа",
    english: "hail",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 10,
    src: require("../../assets/nature/events/smoke.webp"),
    category: "Явления / окружающая среда",
    russian: "дым",
    khadar: "эръа",
    english: "smoke",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 11,
    src: require("../../assets/nature/events/star.webp"),
    category: "Явления / окружающая среда",
    russian: "звезда",
    khadar: "уръи",
    english: "star",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 12,
    src: require("../../assets/nature/events/ground.webp"),
    category: "Явления / окружающая среда",
    russian: "земля",
    khadar: "гонзари",
    english: "ground",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 13,
    src: require("../../assets/nature/events/hoarfrost.webp"),
    category: "Явления / окружающая среда",
    russian: "иней",
    khadar: "сулугъа",
    english: "hoarfrost",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 14,
    src: require("../../assets/nature/events/stone.webp"),
    category: "Явления / окружающая среда",
    russian: "камень",
    khadar: "гъархъа",
    english: "stone",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 15,
    src: require("../../assets/nature/events/drop.webp"),
    category: "Явления / окружающая среда",
    russian: "капля",
    khadar: "кIантI",
    english: "drop",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 16,
    src: require("../../assets/nature/events/sea.webp"),
    category: "Явления / окружающая среда",
    russian: "море",
    khadar: "урхьне",
    english: "sea",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 17,
    src: require("../../assets/nature/events/frost.webp"),
    category: "Явления / окружающая среда",
    russian: "мороз",
    khadar: "даръ",
    english: "frost",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 18,
    src: require("../../assets/nature/events/sky.webp"),
    category: "Явления / окружающая среда",
    russian: "небо",
    khadar: "зубре",
    english: "sky",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 19,
    src: require("../../assets/nature/events/fire.webp"),
    category: "Явления / окружающая среда",
    russian: "огонь",
    khadar: "цIа",
    english: "fire",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 20,
    src: require("../../assets/nature/events/web.webp"),
    category: "Явления / окружающая среда",
    russian: "паутина",
    khadar: "ав",
    english: "web",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 21,
    src: require("../../assets/nature/events/ash.webp"),
    category: "Явления / окружающая среда",
    russian: "пепел",
    khadar: "палда",
    english: "ash",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 22,
    src: require("../../assets/nature/events/soil.webp"),
    category: "Явления / окружающая среда",
    russian: "почва",
    khadar: "гIяижи",
    english: "soil",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 23,
    src: require("../../assets/nature/events/blizzard.webp"),
    category: "Явления / окружающая среда",
    russian: "пурга",
    khadar: "бурам",
    english: "blizzard",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 24,
    src: require("../../assets/nature/events/dust.webp"),
    category: "Явления / окружающая среда",
    russian: "пыль",
    khadar: "хум",
    english: "dust",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 25,
    src: require("../../assets/nature/events/rainbow.webp"),
    category: "Явления / окружающая среда",
    russian: "радуга",
    khadar: "зурхIаб",
    english: "rainbow",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 26,
    src: require("../../assets/nature/events/river.webp"),
    category: "Явления / окружающая среда",
    russian: "река",
    khadar: "хIаркI",
    english: "river",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 27,
    src: require("../../assets/nature/events/light.webp"),
    category: "Явления / окружающая среда",
    russian: "свет",
    khadar: "щаI",
    english: "light",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 28,
    src: require("../../assets/nature/events/snow.webp"),
    category: "Явления / окружающая среда",
    russian: "снег",
    khadar: "дирив",
    english: "snow",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 29,
    src: require("../../assets/nature/events/sun.webp"),
    category: "Явления / окружающая среда",
    russian: "солнце",
    khadar: "бирхIи",
    english: "sun",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 30,
    src: require("../../assets/nature/events/fog.webp"),
    category: "Явления / окружающая среда",
    russian: "туман",
    khadar: "дирав",
    english: "fog",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 31,
    src: require("../../assets/nature/events/seeds.webp"),
    category: "Явления / окружающая среда",
    russian: "семена",
    khadar: "гье",
    english: "seeds",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 32,
    src: require("../../assets/nature/events/oil.webp"),
    category: "Явления / окружающая среда",
    russian: "нефть",
    khadar: "нап",
    english: "oil",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 33,
    src: require("../../assets/nature/events/moon.webp"),
    category: "Явления / окружающая среда",
    russian: "луна",
    khadar: "бас",
    english: "moon",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 34,
    src: require("../../assets/nature/events/puddle.webp"),
    category: "Явления / окружающая среда",
    russian: "лужа",
    khadar: "щара",
    english: "puddle",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 35,
    src: require("../../assets/nature/events/dew.webp"),
    category: "Явления / окружающая среда",
    russian: "роса",
    khadar: "марка",
    english: "dew",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 36,
    src: require("../../assets/nature/events/waterfall.webp"),
    category: "Явления / окружающая среда",
    russian: "водопад",
    khadar: "чахIчахI",
    english: "waterfall",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 37,
    src: require("../../assets/nature/events/cave.webp"),
    category: "Явления / окружающая среда",
    russian: "пещера",
    khadar: "анакъ",
    english: "cave",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 38,
    src: require("../../assets/nature/events/pond.webp"),
    category: "Явления / окружающая среда",
    russian: "пруд",
    khadar: "кIав",
    english: "pond",
    additional_info: "Можно использовать как \"водоём\".",
    sound_src: "apple.m4a",
  },]