export const eventsData = [{
    id: 1,
    src: require("../../assets/events/coast.png"),
    category: "Явления / окружающая среда",
    russian: "берег",
    khadar: "дуб",
    english: "coast",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 2,
    src: require("../../assets/events/wind.png"),
    category: "Явления / окружающая среда",
    russian: "ветер",
    khadar: "букма",
    english: "wind",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 3,
    src: require("../../assets/events/air.png"),
    category: "Явления / окружающая среда",
    russian: "воздух",
    khadar: "гьава",
    english: "air",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 4,
    src: require("../../assets/events/clay.png"),
    category: "Явления / окружающая среда",
    russian: "глина",
    khadar: "гIянжи",
    english: "clay",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 5,
    src: require("../../assets/events/mountain.png"),
    category: "Явления / окружающая среда",
    russian: "гора",
    khadar: "дубура",
    english: "mountain",
    additional_info: "",
    sound_src: "apple.m4a",
  },]