export const fruitData = [
  {
    id: 1,
    src: require("../../assets/food/fruit/apple.webp"),
    category: "Фрукты",
    russian: "яблоко",
    khadar: "гIинц",
    english: "apple",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 2,
    src: require("../../assets/food/fruit/apricot.webp"),
    category: "Фрукты",
    russian: "абрикос",
    khadar: "корага",
    english: "apricot",
    additional_info: "",
    sound_src: "apricot.m4a",
  },
  {
    id: 3,
    src: require("../../assets/food/fruit/quince.webp"),
    category: "Фрукты",
    russian: "айва",
    khadar: "гимиргьи",
    english: "quince",
    additional_info: "",
    sound_src: "quince.m4a",
  },
  {
    id: 4,
    src: require("../../assets/food/fruit/cherry_plum.webp"),
    category: "Фрукты",
    russian: "алыча",
    khadar: "цимихI",
    english: "cherry plum",
    additional_info: "",
    sound_src: "cherry_plum.m4a",
  },
  {
    id: 5,
    src: require("../../assets/food/fruit/grape.webp"),
    category: "Фрукты",
    russian: "виноград",
    khadar: "тIутIи",
    english: "grape",
    additional_info: "",
    sound_src: "grape.m4a",
  },
  {
    id: 6,
    src: require("../../assets/food/fruit/pear.webp"),
    category: "Фрукты",
    russian: "груша",
    khadar: "алмут",
    english: "pear",
    additional_info: "",
    sound_src: "pear.m4a",
  },
  {
    id: 7,
    src: require("../../assets/food/fruit/plum.webp"),
    category: "Фрукты",
    russian: "слива",
    khadar: "кIакIан",
    english: "plum",
    additional_info: "",
    sound_src: "plum.m4a",
  },
  {
    id: 8,
    src: require("../../assets/food/fruit/pumpkin.webp"),
    category: "Фрукты",
    russian: "тыква",
    khadar: "гонзари",
    english: "pumpkin",
    additional_info: "",
    sound_src: "pumpkin.m4a",
  },
  {
    id: 9,
    src: require("../../assets/food/fruit/date.webp"),
    category: "Фрукты",
    russian: "финик",
    khadar: "финик",
    english: "date",
    additional_info: "",
    sound_src: "date.m4a",
  },
  {
    id: 10,
    src: require("../../assets/food/fruit/fruit.webp"),
    category: "Фрукты",
    russian: "фрукты",
    khadar: "цIедехь",
    english: "fruit",
    additional_info: "",
    sound_src: "fruit.m4a",
  }, 
  {
    id: 11,
    src: require("../../assets/food/fruit/peach.webp"),
    category: "Фрукты",
    russian: "персик",
    khadar: "щаптIал",
    english: "peach",
    additional_info: "",
    sound_src: "fruit.m4a",
  }, 
];
