export const furnitureData = [
  {
    id: 1,
    src: require("../../assets/furniture/door.png"),
    category: "Материалы",
    russian: "дверь",
    khadar: "унза",
    english: "door",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 2,
    src: require("../../assets/furniture/curtain.png"),
    category: "Материалы",
    russian: "занавес",
    khadar: "пирда",
    english: "curtain",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 3,
    src: require("../../assets/furniture/bed.png"),
    category: "Материалы",
    russian: "кровать",
    khadar: "карват",
    english: "bed",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 4,
    src: require("../../assets/furniture/stairs.png"),
    category: "Материалы",
    russian: "лестница",
    khadar: "ганзи",
    english: "stairs",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 5,
    src: require("../../assets/furniture/mattress.png"),
    category: "Материалы",
    russian: "матрас",
    khadar: "буруш",
    english: "mattress",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 6,
    src: require("../../assets/furniture/closet.png"),
    category: "Материалы",
    russian: "шкаф",
    khadar: "шипанер",
    english: "closet",
    additional_info:
      "Также шкафы для одежды имеют английский эквивалент wardrobe. Шкафы для посуды называют cupboard.",
    sound_src: "apple.m4a",
  },
  {
    id: 7,
    src: require("../../assets/furniture/shelf.png"),
    category: "Материалы",
    russian: "полка",
    khadar: "тахча",
    english: "shelf",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 8,
    src: require("../../assets/furniture/table.png"),
    category: "Материалы",
    russian: "стол",
    khadar: "истIул",
    english: "table",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 9,
    src: require("../../assets/furniture/roof.png"),
    category: "Материалы",
    russian: "крыша",
    khadar: "хъялхъи",
    english: "roof",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 10,
    src: require("../../assets/furniture/lamp.png"),
    category: "Материалы",
    russian: "лампа",
    khadar: "лампушкIа",
    english: "lamp",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 11,
    src: require("../../assets/furniture/carpet.png"),
    category: "Материалы",
    russian: "ковер",
    khadar: "хали",
    english: "carpet",
    additional_info: "",
    sound_src: "apple.m4a",
  },
];
