export const furnitureData = [
  {
    id: 1,
    src: require("../../assets/furniture/door.webp"),
    category: "Материалы",
    russian: "дверь",
    khadar: "унза",
    english: "door",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 2,
    src: require("../../assets/furniture/curtain.webp"),
    category: "Материалы",
    russian: "занавес",
    khadar: "пирда",
    english: "curtain",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 3,
    src: require("../../assets/furniture/bed.webp"),
    category: "Материалы",
    russian: "кровать",
    khadar: "карват",
    english: "bed",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 4,
    src: require("../../assets/furniture/stairs.webp"),
    category: "Материалы",
    russian: "лестница",
    khadar: "ганзи",
    english: "stairs",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 5,
    src: require("../../assets/furniture/mattress.webp"),
    category: "Материалы",
    russian: "матрас",
    khadar: "буруш",
    english: "mattress",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 6,
    src: require("../../assets/furniture/closet.webp"),
    category: "Материалы",
    russian: "шкаф",
    khadar: "шипанер",
    english: "closet",
    additional_info:
      "Также шкафы для одежды имеют английский эквивалент wardrobe. Шкафы для посуды называют cupboard.",
    sound_src: "apple.m4a",
  },
  {
    id: 7,
    src: require("../../assets/furniture/shelf.webp"),
    category: "Материалы",
    russian: "полка",
    khadar: "тахча",
    english: "shelf",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 8,
    src: require("../../assets/furniture/table.webp"),
    category: "Материалы",
    russian: "стол",
    khadar: "истIул",
    english: "table",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 9,
    src: require("../../assets/furniture/roof.webp"),
    category: "Материалы",
    russian: "крыша",
    khadar: "хъялхъи",
    english: "roof",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 10,
    src: require("../../assets/furniture/lamp.webp"),
    category: "Материалы",
    russian: "лампа",
    khadar: "лампушкIа",
    english: "lamp",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 11,
    src: require("../../assets/furniture/floor.webp"),
    category: "Материалы",
    russian: "пол",
    khadar: "чабар",
    english: "floor",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 12,
    src: require("../../assets/furniture/ceiling.webp"),
    category: "Материалы",
    russian: "потолок",
    khadar: "бурх",
    english: "ceiling",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 13,
    src: require("../../assets/furniture/wall.webp"),
    category: "Материалы",
    russian: "стена",
    khadar: "тIам",
    english: "wall",
    additional_info: "",
    sound_src: "apple.m4a",
  },
];
