export const grainData = [
  {
    id: 1,
    src: require("../../assets/grain/pancake.png"),
    category: "Злаки, зерновые, их производные",
    russian: "блин",
    khadar: "барщанаги",
    english: "pancake",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 2,
    src: require("../../assets/grain/yeast_dough.png"),
    category: "Злаки, зерновые, их производные",
    russian: "дрожжевое тесто",
    khadar: "хамир",
    english: "yeast dough",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 3,
    src: require("../../assets/grain/groats.png"),
    category: "Злаки, зерновые, их производные",
    russian: "крупа",
    khadar: "курпа",
    english: "groats",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 4,
    src: require("../../assets/grain/corn.png"),
    category: "Злаки, зерновые, их производные",
    russian: "кукуруза",
    khadar: "хIежненке",
    english: "corn",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 5,
    src: require("../../assets/grain/corn_flour.png"),
    category: "Злаки, зерновые, их производные",
    russian: "кукурузная мука",
    khadar: "мучере",
    english: "corn flour",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 6,
    src: require("../../assets/grain/flour.png"),
    category: "Злаки, зерновые, их производные",
    russian: "мука",
    khadar: "декъ",
    english: "flour",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 7,
    src: require("../../assets/grain/millet.png"),
    category: "Злаки, зерновые, их производные",
    russian: "просо",
    khadar: "мучи",
    english: "millet",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 8,
    src: require("../../assets/grain/wheat.png"),
    category: "Злаки, зерновые, их производные",
    russian: "пшеница",
    khadar: "анкIи",
    english: "wheat",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 9,
    src: require("../../assets/grain/rice.png"),
    category: "Злаки, зерновые, их производные",
    russian: "рис",
    khadar: "дуги",
    english: "rice",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 10,
    src: require("../../assets/grain/layered_bread.png"),
    category: "Злаки, зерновые, их производные",
    russian: "слоеный хлеб",
    khadar: "гъатламаги",
    english: "layered bread",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 11,
    src: require("../../assets/grain/dough.png"),
    category: "Злаки, зерновые, их производные",
    russian: "тесто",
    khadar: "бащанаги",
    english: "dough",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 12,
    src: require("../../assets/grain/bread.png"),
    category: "Злаки, зерновые, их производные",
    russian: "хлеб",
    khadar: "азихъ",
    english: "bread",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 13,
    src: require("../../assets/grain/barley.png"),
    category: "Злаки, зерновые, их производные",
    russian: "ячмень",
    khadar: "мухъа",
    english: "barley",
    additional_info: "",
    sound_src: "apple.m4a",
  },
];
