export const grainData = [
  {
    id: 2,
    src: require("../../assets/food/grain/yeast_dough.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "дрожжевое тесто",
    khadar: "хамир",
    english: "yeast dough",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 3,
    src: require("../../assets/food/grain/groats.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "крупа",
    khadar: "курпа",
    english: "groats",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 4,
    src: require("../../assets/food/grain/corn.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "кукуруза",
    khadar: "хIежненке",
    english: "corn",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 5,
    src: require("../../assets/food/grain/corn_flour.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "кукурузная мука",
    khadar: "мучере",
    english: "corn flour",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 6,
    src: require("../../assets/food/grain/flour.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "мука",
    khadar: "декъ",
    english: "flour",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 7,
    src: require("../../assets/food/grain/millet.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "просо",
    khadar: "мучи",
    english: "millet",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 8,
    src: require("../../assets/food/grain/wheat.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "пшеница",
    khadar: "анкIи",
    english: "wheat",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 9,
    src: require("../../assets/food/grain/rice.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "рис",
    khadar: "дуги",
    english: "rice",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 10,
    src: require("../../assets/food/grain/layered_bread.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "слоеный хлеб",
    khadar: "гъатламаги",
    english: "layered bread",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 11,
    src: require("../../assets/food/grain/dough.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "тесто",
    khadar: "бащанаги",
    english: "dough",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 12,
    src: require("../../assets/food/grain/bread.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "хлеб",
    khadar: "азихъ",
    english: "bread",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 13,
    src: require("../../assets/food/grain/barley.webp"),
    category: "Злаки, зерновые, их производные",
    russian: "ячмень",
    khadar: "мухъа",
    english: "barley",
    additional_info: "",
    sound_src: "apple.m4a",
  },
];
