export const insectsData = [
    {
        id: 1,
        src: require("../../assets/insects/butterfly.png"),
        category: "Насекомые",
        russian: "бабочка",
        khadar: "хаминдари",
        english: "butterfly",
        additional_info: "",
        sound_src: "apple.m4a",
    },
    {
        id: 2,
        src: require("../../assets/insects/dragonfly.png"),
        category: "Насекомые",
        russian: "стрекоза",
        khadar: "цIерцI",
        english: "dragonfly",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/insects/beetle.png"),
        category: "Насекомые",
        russian: "жук",
        khadar: "тусахIари",
        english: "beetle",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/insects/mite.png"),
        category: "Насекомые",
        russian: "клещ",
        khadar: "кIакIари",
        english: "mite",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/insects/fly.png"),
        category: "Насекомые",
        russian: "муха",
        khadar: "кIент",
        english: "fly",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 6,
        src: require("../../assets/insects/grasshopper.png"),
        category: "Насекомые",
        russian: "кузнечик",
        khadar: "урцIецIе",
        english: "grasshopper",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 7,
        src: require("../../assets/insects/moth.png"),
        category: "Насекомые",
        russian: "моль",
        khadar: "имс",
        english: "moth",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 8,
        src: require("../../assets/insects/hornet.png"),
        category: "Насекомые",
        russian: "оса",
        khadar: "гIиндир",
        english: "hornet",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 9,
        src: require("../../assets/insects/bee.png"),
        category: "Насекомые",
        russian: "пчела",
        khadar: "мирхъи",
        english: "bee",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 10,
        src: require("../../assets/insects/mole_cricket.png"),
        category: "Насекомые",
        russian: "медведка",
        khadar: "безалтуш",
        english: "mole cricket",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      
]