export const mammalsData = [
    {
        id: 1,
        src: require("../../assets/mammals/ram.png"),
        category: "Млекопитающиеся",
        russian: "баран",
        khadar: "мас",
        english: "ram",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 2,
        src: require("../../assets/mammals/buffalo.png"),
        category: "Млекопитающиеся",
        russian: "буйвол",
        khadar: "гамущ",
        english: "buffalo",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/mammals/bull.png"),
        category: "Млекопитающиеся",
        russian: "бык",
        khadar: "бугъа",
        english: "bull",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/mammals/camel.png"),
        category: "Млекопитающиеся",
        russian: "верблюд",
        khadar: "валреъ",
        english: "camel",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/mammals/wolf.png"),
        category: "Млекопитающиеся",
        russian: "волк",
        khadar: "бецI",
        english: "wolf",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 6,
        src: require("../../assets/mammals/gazelle.png"),
        category: "Млекопитающиеся",
        russian: "газель",
        khadar: "жайран",
        english: "gazelle",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 7,
        src: require("../../assets/mammals/dragon.png"),
        category: "Млекопитающиеся",
        russian: "дракон",
        khadar: "аждагьа",
        english: "dragon",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 8,
        src: require("../../assets/mammals/hedgehog.png"),
        category: "Млекопитающиеся",
        russian: "еж",
        khadar: "кирпи",
        english: "hedgehog",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 9,
        src: require("../../assets/mammals/goat.png"),
        category: "Млекопитающиеся",
        russian: "козел",
        khadar: "гIяжа",
        english: "goat",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 10,
        src: require("../../assets/mammals/cow.png"),
        category: "Млекопитающиеся",
        russian: "корова",
        khadar: "къал",
        english: "cow",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 11,
        src: require("../../assets/mammals/cat.png"),
        category: "Млекопитающиеся",
        russian: "кошка",
        khadar: "кату",
        english: "cat",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 12,
        src: require("../../assets/mammals/rabbit.png"),
        category: "Млекопитающиеся",
        russian: "кролик",
        khadar: "гIяри",
        english: "rabbit",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 13,
        src: require("../../assets/mammals/lion.png"),
        category: "Млекопитающиеся",
        russian: "лев",
        khadar: "арслангъатла",
        english: "lion",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 14,
        src: require("../../assets/mammals/fox.png"),
        category: "Млекопитающиеся",
        russian: "лиса",
        khadar: "гурда",
        english: "fox",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 15,
        src: require("../../assets/mammals/horse.png"),
        category: "Млекопитающиеся",
        russian: "лошадь",
        khadar: "ябу",
        english: "horse",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 16,
        src: require("../../assets/mammals/bear.png"),
        category: "Млекопитающиеся",
        russian: "медведь",
        khadar: "синка",
        english: "bear",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 17,
        src: require("../../assets/mammals/mouse.png"),
        category: "Млекопитающиеся",
        russian: "мышь",
        khadar: "гоца",
        english: "mouse",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 18,
        src: require("../../assets/mammals/monkey.png"),
        category: "Млекопитающиеся",
        russian: "обезьяна",
        khadar: "маймун",
        english: "monkey",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 19,
        src: require("../../assets/mammals/sheep.png"),
        category: "Млекопитающиеся",
        russian: "овца",
        khadar: "маза",
        english: "sheep",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 20,
        src: require("../../assets/mammals/donkey.png"),
        category: "Млекопитающиеся",
        russian: "осел",
        khadar: "хIамхIа",
        english: "donkey",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 21,
        src: require("../../assets/mammals/pig.png"),
        category: "Млекопитающиеся",
        russian: "свинья",
        khadar: "цура",
        english: "pig",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 22,
        src: require("../../assets/mammals/elephant.png"),
        category: "Млекопитающиеся",
        russian: "слон",
        khadar: "пил",
        english: "elephant",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 23,
        src: require("../../assets/mammals/tiger.png"),
        category: "Млекопитающиеся",
        russian: "тигр",
        khadar: "къаплан",
        english: "tiger",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 24,
        src: require("../../assets/mammals/jackal.png"),
        category: "Млекопитающиеся",
        russian: "шакал",
        khadar: "хIахIбецI",
        english: "camel",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 25,
        src: require("../../assets/mammals/mutt.png"),
        category: "Млекопитающиеся",
        russian: "щенок",
        khadar: "кIулай",
        english: "mutt",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 26,
        src: require("../../assets/mammals/herd.png"),
        category: "Млекопитающиеся",
        russian: "стадо",
        khadar: "хIанкъ",
        english: "herd",
        additional_info: "",
        sound_src: "apple.m4a",
      },
]