export const mammalsData = [
    {
        id: 1,
        src: require("../../assets/animals/mammals/ram.webp"),
        category: "Млекопитающиеся",
        russian: "баран",
        khadar: "мас",
        english: "ram",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 2,
        src: require("../../assets/animals/mammals/buffalo.webp"),
        category: "Млекопитающиеся",
        russian: "буйвол",
        khadar: "гамущ",
        english: "buffalo",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/animals/mammals/bull.webp"),
        category: "Млекопитающиеся",
        russian: "бык",
        khadar: "бугъа",
        english: "bull",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/animals/mammals/camel.webp"),
        category: "Млекопитающиеся",
        russian: "верблюд",
        khadar: "валреъ",
        english: "camel",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/animals/mammals/wolf.webp"),
        category: "Млекопитающиеся",
        russian: "волк",
        khadar: "бецI",
        english: "wolf",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 6,
        src: require("../../assets/animals/mammals/gazelle.webp"),
        category: "Млекопитающиеся",
        russian: "газель",
        khadar: "жайран",
        english: "gazelle",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 7,
        src: require("../../assets/animals/mammals/dragon.webp"),
        category: "Млекопитающиеся",
        russian: "дракон",
        khadar: "аждагьа",
        english: "dragon",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 8,
        src: require("../../assets/animals/mammals/hedgehog.webp"),
        category: "Млекопитающиеся",
        russian: "еж",
        khadar: "кирпи",
        english: "hedgehog",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 9,
        src: require("../../assets/animals/mammals/goat.webp"),
        category: "Млекопитающиеся",
        russian: "козел",
        khadar: "гIяжа",
        english: "goat",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 10,
        src: require("../../assets/animals/mammals/cow.webp"),
        category: "Млекопитающиеся",
        russian: "корова",
        khadar: "къал",
        english: "cow",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 11,
        src: require("../../assets/animals/mammals/cat.webp"),
        category: "Млекопитающиеся",
        russian: "кошка",
        khadar: "кату",
        english: "cat",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 12,
        src: require("../../assets/animals/mammals/rabbit.webp"),
        category: "Млекопитающиеся",
        russian: "кролик",
        khadar: "гIяри",
        english: "rabbit",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 13,
        src: require("../../assets/animals/mammals/lion.webp"),
        category: "Млекопитающиеся",
        russian: "лев",
        khadar: "арслангъатла",
        english: "lion",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 14,
        src: require("../../assets/animals/mammals/fox.webp"),
        category: "Млекопитающиеся",
        russian: "лиса",
        khadar: "гурда",
        english: "fox",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 15,
        src: require("../../assets/animals/mammals/horse.webp"),
        category: "Млекопитающиеся",
        russian: "лошадь",
        khadar: "ябу",
        english: "horse",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 16,
        src: require("../../assets/animals/mammals/bear.webp"),
        category: "Млекопитающиеся",
        russian: "медведь",
        khadar: "синка",
        english: "bear",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 17,
        src: require("../../assets/animals/mammals/mouse.webp"),
        category: "Млекопитающиеся",
        russian: "мышь",
        khadar: "гоца",
        english: "mouse",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 18,
        src: require("../../assets/animals/mammals/monkey.webp"),
        category: "Млекопитающиеся",
        russian: "обезьяна",
        khadar: "маймун",
        english: "monkey",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 19,
        src: require("../../assets/animals/mammals/sheep.webp"),
        category: "Млекопитающиеся",
        russian: "овца",
        khadar: "маза",
        english: "sheep",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 20,
        src: require("../../assets/animals/mammals/donkey.webp"),
        category: "Млекопитающиеся",
        russian: "осел",
        khadar: "хIамхIа",
        english: "donkey",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 21,
        src: require("../../assets/animals/mammals/pig.webp"),
        category: "Млекопитающиеся",
        russian: "свинья",
        khadar: "цура",
        english: "pig",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 22,
        src: require("../../assets/animals/mammals/elephant.webp"),
        category: "Млекопитающиеся",
        russian: "слон",
        khadar: "пил",
        english: "elephant",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 23,
        src: require("../../assets/animals/mammals/tiger.webp"),
        category: "Млекопитающиеся",
        russian: "тигр",
        khadar: "къаплан",
        english: "tiger",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 24,
        src: require("../../assets/animals/mammals/jackal.webp"),
        category: "Млекопитающиеся",
        russian: "шакал",
        khadar: "хIахIбецI",
        english: "camel",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 25,
        src: require("../../assets/animals/mammals/mutt.webp"),
        category: "Млекопитающиеся",
        russian: "щенок",
        khadar: "кIулай",
        english: "mutt",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 26,
        src: require("../../assets/animals/mammals/herd.webp"),
        category: "Млекопитающиеся",
        russian: "стадо",
        khadar: "хIанкъ",
        english: "herd",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 27,
        src: require("../../assets/animals/mammals/dog.webp"),
        category: "Млекопитающиеся",
        russian: "собака",
        khadar: "хо",
        english: "dog",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 28,
        src: require("../../assets/animals/mammals/rat.webp"),
        category: "Ползучие",
        russian: "крыса",
        khadar: "къургугваца",
        english: "rat",
        additional_info: "",
        sound_src: "apple.m4a",
      },
]