export const materialsData = [
    {
      id: 1,
      src: require("../../assets/materials/aluminium.webp"),
      category: "Материалы",
      russian: "алюминий",
      khadar: "тутия",
      english: "aluminium",
      additional_info: "",
      sound_src: "apple.m4a",
    },
    {
        id: 2,
        src: require("../../assets/materials/gold.webp"),
        category: "Материалы",
        russian: "золото",
        khadar: "мургье",
        english: "gold",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/materials/silver.webp"),
        category: "Материалы",
        russian: "серебро",
        khadar: "мигь",
        english: "silver",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/materials/ivory.webp"),
        category: "Материалы",
        russian: "слоновая кость",
        khadar: "магьи",
        english: "ivory",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/materials/steel.webp"),
        category: "Материалы",
        russian: "сталь",
        khadar: "шандан",
        english: "steel",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 6,
        src: require("../../assets/materials/glass.webp"),
        category: "Материалы",
        russian: "стекло",
        khadar: "шиша",
        english: "glass",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 7,
        src: require("../../assets/materials/china.webp"),
        category: "Материалы",
        russian: "фарфор",
        khadar: "чини",
        english: "china",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 8,
        src: require("../../assets/materials/amber.webp"),
        category: "Материалы",
        russian: "янтарь",
        khadar: "юсру",
        english: "amber",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 9,
        src: require("../../assets/materials/paper.webp"),
        category: "Материалы",
        russian: "бумага",
        khadar: "къагъат",
        english: "paper",
        additional_info: "\"Къагъат\" также имеет значение \"письмо\".",
        sound_src: "apple.m4a",
      },
]