export const otherData = [
  {
    id: 3,
    src: require("../../assets/food/other/water.webp"),
    category: "Другое",
    russian: "вода",
    khadar: "шин",
    english: "water",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 4,
    src: require("../../assets/food/other/vodka.webp"),
    category: "Другое",
    russian: "водка",
    khadar: "хIярякьи",
    english: "vodka",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 5,
    src: require("../../assets/food/other/walnut.webp"),
    category: "Другое",
    russian: "грецкий орех",
    khadar: "гъиве",
    english: "walnut",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 6,
    src: require("../../assets/food/other/wine.webp"),
    category: "Другое",
    russian: "вино",
    khadar: "чагьир",
    english: "wine",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 7,
    src: require("../../assets/food/other/mushroom.webp"),
    category: "Другое",
    russian: "гриб",
    khadar: "къашкъар",
    english: "mushroom",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 8,
    src: require("../../assets/food/other/food.webp"),
    category: "Другое",
    russian: "еда",
    khadar: "берконе",
    english: "food",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 9,
    src: require("../../assets/food/other/candy.webp"),
    category: "Другое",
    russian: "конфета",
    khadar: "кемпет",
    english: "candy",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 10,
    src: require("../../assets/food/other/slice.webp"),
    category: "Другое",
    russian: "кусок",
    khadar: "къац",
    english: "slice",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 11,
    src: require("../../assets/food/other/lemonade.webp"),
    category: "Другое",
    russian: "лимонад",
    khadar: "лиманат",
    english: "lemonade",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 12,
    src: require("../../assets/food/other/honey.webp"),
    category: "Другое",
    russian: "мед",
    khadar: "варъа",
    english: "honey",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 13,
    src: require("../../assets/food/other/egg.webp"),
    category: "Другое",
    russian: "яйцо",
    khadar: "гигари",
    english: "egg",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 14,
    src: require("../../assets/food/other/hazelnut.webp"),
    category: "Другое",
    russian: "фундук",
    khadar: "сирмуга",
    english: "hazelnut",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 15,
    src: require("../../assets/food/other/nut.webp"),
    category: "Другое",
    russian: "орех",
    khadar: "гъив",
    english: "nut",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 16,
    src: require("../../assets/food/other/olive.webp"),
    category: "Другое",
    russian: "оливка",
    khadar: "зайтун",
    english: "olive",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 17,
    src: require("../../assets/food/other/pepper.webp"),
    category: "Другое",
    russian: "перец",
    khadar: "жибжи",
    english: "pepper",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 18,
    src: require("../../assets/food/other/salt.webp"),
    category: "Другое",
    russian: "соль",
    khadar: "зеъ",
    english: "salt",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 19,
    src: require("../../assets/food/other/scrambled_eggs.webp"),
    category: "Другое",
    russian: "яичница",
    khadar: "гигала гъайнакъ",
    english: "scrambled eggs",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 20,
    src: require("../../assets/food/other/sugar.webp"),
    category: "Другое",
    russian: "сахар",
    khadar: "шекер",
    english: "sugar",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  ];