export const timeData = [
  {
    src: require("../../assets/time/spring.webp"),
    category: "time",
    russian: "весна",
    khadar: "хIюяб",
    english: "spring",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/summer.webp"),
    category: "time",
    russian: "лето",
    khadar: "дуцмур",
    english: "summer",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/autumn.webp"),
    category: "time",
    russian: "осень",
    khadar: "бехьни",
    english: "autumn",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/winter.webp"),
    category: "time",
    russian: "зима",
    khadar: "эни",
    english: "winter",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/morning.webp"),
    category: "time",
    russian: "утро",
    khadar: "салау",
    english: "morning",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/evening.webp"),
    category: "time",
    russian: "вечер",
    khadar: "берхакъ",
    english: "evening",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/night.webp"),
    category: "time",
    russian: "ночь",
    khadar: "дуге",
    english: "night",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/second.webp"),
    category: "time",
    russian: "секунда",
    khadar: "секунд",
    english: "second",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/minute.webp"),
    category: "time",
    russian: "минута",
    khadar: "минут",
    english: "minute",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/hour.webp"),
    category: "time",
    russian: "час",
    khadar: "саат",
    english: "hour",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/day.webp"),
    category: "time",
    russian: "день",
    khadar: "бари",
    english: "day",
    additional_info: 'Также можно истолковать как "дневное время" (daytime).',
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/week.webp"),
    category: "time",
    russian: "неделя",
    khadar: "жумагIя",
    english: "week",
    additional_info: 'Также имеет значение "пятница"',
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/month.webp"),
    category: "time",
    russian: "месяц",
    khadar: "бас",
    english: "month",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/time/year.webp"),
    category: "time",
    russian: "год",
    khadar: "дус",
    english: "year",
    additional_info: "",
    sound_src: "apple.m4a",
  },
];
