export const utensilsData = [{
    id: 1,
    src: require("../../assets/utensils/saucer.webp"),
    category: "Кухонная утварь",
    russian: "блюдце",
    khadar: "нарбики",
    english: "saucer",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 2,
    src: require("../../assets/utensils/fork.webp"),
    category: "Кухонная утварь",
    russian: "вилка",
    khadar: "бултане",
    english: "fork",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 3,
    src: require("../../assets/utensils/soup_plate.webp"),
    category: "Кухонная утварь",
    russian: "глубокая тарелка",
    khadar: "сукра",
    english: "soup plate",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 4,
    src: require("../../assets/utensils/colander.webp"),
    category: "Кухонная утварь",
    russian: "дуршлаг",
    khadar: "чулпу",
    english: "colander",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 5,
    src: require("../../assets/utensils/pot.webp"),
    category: "Кухонная утварь",
    russian: "кастрюля",
    khadar: "щенк",
    english: "pot",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 6,
    src: require("../../assets/utensils/mug.webp"),
    category: "Кухонная утварь",
    russian: "кружка",
    khadar: "крушка",
    english: "mug",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 7,
    src: require("../../assets/utensils/bowl.webp"),
    category: "Кухонная утварь",
    russian: "миска",
    khadar: "гIям",
    english: "bowl",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 8,
    src: require("../../assets/utensils/knife.webp"),
    category: "Кухонная утварь",
    russian: "нож",
    khadar: "дис",
    english: "knife",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 9,
    src: require("../../assets/utensils/tray.webp"),
    category: "Кухонная утварь",
    russian: "поднос",
    khadar: "кIабатI",
    english: "tray",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 10,
    src: require("../../assets/utensils/ladle.webp"),
    category: "Кухонная утварь",
    russian: "половник",
    khadar: "чумуч",
    english: "ladle",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 11,
    src: require("../../assets/utensils/glass.webp"),
    category: "Кухонная утварь",
    russian: "стакан",
    khadar: "истакан",
    english: "glass",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 12,
    src: require("../../assets/utensils/plate.webp"),
    category: "Кухонная утварь",
    russian: "тарелка",
    khadar: "бушхап",
    english: "plate",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 13,
    src: require("../../assets/utensils/grater.webp"),
    category: "Кухонная утварь",
    russian: "терка",
    khadar: "терка",
    english: "grater",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 14,
    src: require("../../assets/utensils/apron.webp"),
    category: "Кухонная утварь",
    russian: "фартук",
    khadar: "пяртук",
    english: "apron",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 15,
    src: require("../../assets/utensils/cup.webp"),
    category: "Кухонная утварь",
    russian: "чашка",
    khadar: "щашка",
    english: "cup",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 16,
    src: require("../../assets/utensils/skimmer.webp"),
    category: "Кухонная утварь",
    russian: "шумовка",
    khadar: "квашин",
    english: "skimmer",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 17,
    src: require("../../assets/utensils/kettle.webp"),
    category: "Кухонная утварь",
    russian: "чайник",
    khadar: "чайник",
    english: "kettle",
    additional_info: "",
    sound_src: "apple.m4a",
  }, ]