export const vegetablesData = [
    {
      id: 1,
      src: require("../../assets/food/vegetables/cabbage.webp"),
      category: "Овощи",
      russian: "капуста",
      khadar: "гъапуста",
      english: "cabbage",
      additional_info: "",
      sound_src: "apple.m4a",
    },
    {
      id: 2,
      src: require("../../assets/food/vegetables/onion.webp"),
      category: "Овощи",
      russian: "лук",
      khadar: "зерхьи",
      english: "onion",
      additional_info: "",
      sound_src: "apricot.m4a",
    },
    {
      id: 3,
      src: require("../../assets/food/vegetables/carrot.webp"),
      category: "Овощи",
      russian: "морковь",
      khadar: "намадари",
      english: "carrot",
      additional_info: "",
      sound_src: "quince.m4a",
    },
    {
      id: 4,
      src: require("../../assets/food/vegetables/cucumber.webp"),
      category: "Овощи",
      russian: "огурец",
      khadar: "хIияр",
      english: "cucumber",
      additional_info: "",
      sound_src: "cherry_plum.m4a",
    },
    {
      id: 5,
      src: require("../../assets/food/vegetables/tomato.webp"),
      category: "Овощи",
      russian: "помидор",
      khadar: "памадур",
      english: "tomato",
      additional_info: "",
      sound_src: "grape.m4a",
    },
    {
      id: 6,
      src: require("../../assets/food/vegetables/beet.webp"),
      category: "Овощи",
      russian: "свекла",
      khadar: "кIахIа",
      english: "beet",
      additional_info: "",
      sound_src: "pear.m4a",
    },
    {
      id: 7,
      src: require("../../assets/food/vegetables/bean.webp"),
      category: "Овощи",
      russian: "фасоль",
      khadar: "кIаръа",
      english: "bean",
      additional_info: "",
      sound_src: "plum.m4a",
    },
    {
      id: 8,
      src: require("../../assets/food/vegetables/garlic.webp"),
      category: "Овощи",
      russian: "чеснок",
      khadar: "итанзерхьи",
      english: "garlic",
      additional_info: "",
      sound_src: "pumpkin.m4a",
    },
]