export const weaponsData = [
    {
      id: 1,
      src: require("../../assets/weapons/pistol.webp"),
      category: "Оружия",
      russian: "пистолет",
      khadar: "тапанга",
      english: "pistol",
      additional_info: "",
      sound_src: "apple.m4a",
    },
    {
        id: 2,
        src: require("../../assets/weapons/gunpowder.webp"),
        category: "Оружия",
        russian: "порох",
        khadar: "янсав",
        english: "gunpowder",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 3,
        src: require("../../assets/weapons/bullet.webp"),
        category: "Оружия",
        russian: "пуля",
        khadar: "хIархIа",
        english: "bullet",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 4,
        src: require("../../assets/weapons/cannon.webp"),
        category: "Оружия",
        russian: "пушка",
        khadar: "туп",
        english: "cannon",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 5,
        src: require("../../assets/weapons/rifle.webp"),
        category: "Оружия",
        russian: "ружье",
        khadar: "тупанг",
        english: "rifle",
        additional_info: "",
        sound_src: "apple.m4a",
      },
      {
        id: 6,
        src: require("../../assets/weapons/sabre.webp"),
        category: "Оружия",
        russian: "сабля",
        khadar: "мушкIа",
        english: "sabre",
        additional_info: "",
        sound_src: "apple.m4a",
      }, {
        id: 7,
        src: require("../../assets/weapons/arrow.webp"),
        category: "Оружия",
        russian: "стрела",
        khadar: "урчи",
        english: "arrow",
        additional_info: "",
        sound_src: "apple.m4a",
      },
]