export const adverbsData = [
  {
    src: "",
    category: "Наречия",
    russian: "много",
    khadar: "дакъол",
    english: "many / much",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "большинство",
    khadar: "дакъмел",
    english: "majority",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "всегда",
    khadar: "мурталра",
    english: "always",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "ещё",
    khadar: "хатIира",
    english: "more",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "затем",
    khadar: "итирахIа",
    english: "then",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "как",
    khadar: "цен",
    english: "how",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "когда",
    khadar: "мурт",
    english: "when",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "кто",
    khadar: "чин",
    english: "who",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "куда",
    khadar: "кина",
    english: "where",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "мало",
    khadar: "камил",
    english: "few / little",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "но",
    khadar: "ама",
    english: "but",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "откуда",
    khadar: "кинакан",
    english: "where from",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "отсюда",
    khadar: "ишакан",
    english: "from here",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "потому что",
    khadar: "цес хIинану",
    english: "because",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "сколько",
    khadar: "чум",
    english: "how much",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "что",
    khadar: "це",
    english: "what",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "Наречия",
    russian: "что-то",
    khadar: "зат",
    english: "something",
    additional_info: "",
    sound_src: "apple.m4a",
  },
];
