export const verbsData = [
  {
    id: 1,
    src: require("../../assets/verbs/take.webp"),
    category: "Глаголы",
    russian: "брать",
    khadar: "арасес",
    english: "to take",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 2,
    src: require("../../assets/verbs/hang.webp"),
    category: "Глаголы",
    russian: "вешать",
    khadar: "ардирэс",
    english: "to hang",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 3,
    src: require("../../assets/verbs/see.webp"),
    category: "Глаголы",
    russian: "видеть",
    khadar: "кебаэс",
    english: "to see",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 4,
    src: require("../../assets/verbs/drink.webp"),
    category: "Глаголы",
    russian: "пить",
    khadar: "бержес",
    english: "to drink",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 5,
    src: require("../../assets/verbs/speak.webp"),
    category: "Глаголы",
    russian: "говорить",
    khadar: "укIас",
    english: "to speak",
    additional_info: "",
    sound_src: "apple.m4a",
  }, {
    id: 6,
    src: require("../../assets/verbs/burn.webp"),
    category: "Глаголы",
    russian: "гореть",
    khadar: "игос",
    english: "to burn",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 7,
    src: require("../../assets/verbs/do.webp"),
    category: "Глаголы",
    russian: "делать",
    khadar: "барес",
    english: "to do",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 8,
    src: require("../../assets/verbs/live.webp"),
    category: "Глаголы",
    russian: "жить",
    khadar: "яшадиукIас",
    english: "to live",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 9,
    src: require("../../assets/verbs/close.webp"),
    category: "Глаголы",
    russian: "закрывать",
    khadar: "депбарес",
    english: "to close",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 10,
    src: require("../../assets/verbs/know.webp"),
    category: "Глаголы",
    russian: "знать",
    khadar: "багьес",
    english: "to know",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 11,
    src: require("../../assets/verbs/paint.webp"),
    category: "Глаголы",
    russian: "красить",
    khadar: "рандарес",
    english: "to paint",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 12,
    src: require("../../assets/verbs/bite.webp"),
    category: "Глаголы",
    russian: "кусать",
    khadar: "ацIукIас",
    english: "to bite",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 13,
    src: require("../../assets/verbs/like.webp"),
    category: "Глаголы",
    russian: "нравиться",
    khadar: "ахIбизес",
    english: "to like",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 14,
    src: require("../../assets/verbs/need.webp"),
    category: "Глаголы",
    russian: "нуждаться",
    khadar: "гIянес",
    english: "to need",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 15,
    src: require("../../assets/verbs/put_on.webp"),
    category: "Глаголы",
    russian: "надеть",
    khadar: "икIос",
    english: "to put on",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 16,
    src: require("../../assets/verbs/open.webp"),
    category: "Глаголы",
    russian: "открыть",
    khadar: "ипхъес",
    english: "to open",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 17,
    src: require("../../assets/verbs/write.webp"),
    category: "Глаголы",
    russian: "писать",
    khadar: "белкIес",
    english: "to write",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 18,
    src: require("../../assets/verbs/swim.webp"),
    category: "Глаголы",
    russian: "плавать",
    khadar: "юздуукIас",
    english: "to swim",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 19,
    src: require("../../assets/verbs/cry.webp"),
    category: "Глаголы",
    russian: "плакать",
    khadar: "исес",
    english: "to cry",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 20,
    src: require("../../assets/verbs/cover.webp"),
    category: "Глаголы",
    russian: "покрыть",
    khadar: "къаппарес",
    english: "to cover",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 21,
    src: require("../../assets/verbs/bring.webp"),
    category: "Глаголы",
    russian: "приносить",
    khadar: "гатес",
    english: "to bring",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 22,
    src: require("../../assets/verbs/wake_up.webp"),
    category: "Глаголы",
    russian: "проснуться",
    khadar: "тIатIугьес",
    english: "to wake up",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 23,
    src: require("../../assets/verbs/repeat.webp"),
    category: "Глаголы",
    russian: "повторить",
    khadar: "тикрарбарес",
    english: "to repeat",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 24,
    src: require("../../assets/verbs/bow.webp"),
    category: "Глаголы",
    russian: "поклоняться",
    khadar: "суждабарес",
    english: "to bow",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 25,
    src: require("../../assets/verbs/put.webp"),
    category: "Глаголы",
    russian: "положить",
    khadar: "буцес",
    english: "to put",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 26,
    src: require("../../assets/verbs/accept.webp"),
    category: "Глаголы",
    russian: "принять",
    khadar: "кьабулбарес",
    english: "to accept",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 27,
    src: require("../../assets/verbs/say.webp"),
    category: "Глаголы",
    russian: "сказать",
    khadar: "эс",
    english: "to say",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 28,
    src: require("../../assets/verbs/look.webp"),
    category: "Глаголы",
    russian: "смотреть",
    khadar: "тIарукIас",
    english: "to look",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 29,
    src: require("../../assets/verbs/eat.webp"),
    category: "Глаголы",
    russian: "есть",
    khadar: "букес",
    english: "to eat",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 30,
    src: require("../../assets/verbs/increase.webp"),
    category: "Глаголы",
    russian: "увеличить",
    khadar: "дакъбарес",
    english: "to increase",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 31,
    src: require("../../assets/verbs/decrease.webp"),
    category: "Глаголы",
    russian: "уменьшить",
    khadar: "камбарес",
    english: "to decrease",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 32,
    src: require("../../assets/verbs/read.webp"),
    category: "Глаголы",
    russian: "читать",
    khadar: "бучIес",
    english: "to read",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 33,
    src: "",
    category: "Глаголы",
    russian: "являться, быть",
    khadar: "угьес",
    english: "to be",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 34,
    src: require("../../assets/verbs/run.webp"),
    category: "Глаголы",
    russian: "бежать",
    khadar: "дуцукIас",
    english: "to run",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 35,
    src: require("../../assets/verbs/fall.webp"),
    category: "Глаголы",
    russian: "падать",
    khadar: "кайкес",
    english: "to fall",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 36,
    src: require("../../assets/verbs/lay.webp"),
    category: "Глаголы",
    russian: "лежать",
    khadar: "кайхес",
    english: "to lay",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 37,
    src: require("../../assets/verbs/stand.webp"),
    category: "Глаголы",
    russian: "стоять",
    khadar: "айтес",
    english: "to stand",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 38,
    src: require("../../assets/verbs/mow.webp"),
    category: "Глаголы",
    russian: "косить",
    khadar: "ирщес",
    english: "to mow",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 39,
    src: require("../../assets/verbs/find.webp"),
    category: "Глаголы",
    russian: "найти",
    khadar: "баргес",
    english: "to find",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 40,
    src: require("../../assets/verbs/crawl.webp"),
    category: "Глаголы",
    russian: "ползать",
    khadar: "хусукIас",
    english: "to crawl",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 41,
    src: require("../../assets/verbs/show.webp"),
    category: "Глаголы",
    russian: "показать",
    khadar: "къабакъес",
    english: "to show",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 42,
    src: require("../../assets/verbs/be_hungry.webp"),
    category: "Глаголы",
    russian: "проголодаться",
    khadar: "гушуес",
    english: "to be hungry",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 43,
    src: require("../../assets/verbs/cut.webp"),
    category: "Глаголы",
    russian: "резать",
    khadar: "балгъес",
    english: "to cut",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 44,
    src: require("../../assets/verbs/turn_on.webp"),
    category: "Глаголы",
    russian: "включить",
    khadar: "бикьес",
    english: "to turn on",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 45,
    src: require("../../assets/verbs/fly.webp"),
    category: "Глаголы",
    russian: "летать",
    khadar: "урцес",
    english: "to fly",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 46,
    src: require("../../assets/verbs/jump.webp"),
    category: "Глаголы",
    russian: "прыгать",
    khadar: "парсукIас",
    english: "to jump",
    additional_info: "",
    sound_src: "apple.m4a",
  },

];
