export const verbsData = [
  {
    src: require("../../assets/verbs/take.webp"),
    category: "verbs",
    russian: "брать",
    khadar: "арасес",
    english: "to take",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/hang.webp"),
    category: "verbs",
    russian: "вешать",
    khadar: "ардирэс",
    english: "to hang",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/see.webp"),
    category: "verbs",
    russian: "видеть",
    khadar: "кебаэс",
    english: "to see",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/drink.webp"),
    category: "verbs",
    russian: "пить",
    khadar: "бержес",
    english: "to drink",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/speak.webp"),
    category: "verbs",
    russian: "говорить",
    khadar: "укIас",
    english: "to speak",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/burn.webp"),
    category: "verbs",
    russian: "гореть",
    khadar: "игос",
    english: "to burn",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/do.webp"),
    category: "verbs",
    russian: "делать",
    khadar: "барес",
    english: "to do",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/live.webp"),
    category: "verbs",
    russian: "жить",
    khadar: "яшадиукIас",
    english: "to live",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/close.webp"),
    category: "verbs",
    russian: "закрывать",
    khadar: "депбарес",
    english: "to close",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/know.webp"),
    category: "verbs",
    russian: "знать",
    khadar: "багьес",
    english: "to know",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/paint.webp"),
    category: "verbs",
    russian: "красить",
    khadar: "рандарес",
    english: "to paint",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/bite.webp"),
    category: "verbs",
    russian: "кусать",
    khadar: "ацIукIас",
    english: "to bite",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/like.webp"),
    category: "verbs",
    russian: "нравиться",
    khadar: "ахIбизес",
    english: "to like",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/need.webp"),
    category: "verbs",
    russian: "нуждаться",
    khadar: "гIянес",
    english: "to need",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/put_on.webp"),
    category: "verbs",
    russian: "надеть",
    khadar: "икIос",
    english: "to put on",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/open.webp"),
    category: "verbs",
    russian: "открыть",
    khadar: "ипхъес",
    english: "to open",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/write.webp"),
    category: "verbs",
    russian: "писать",
    khadar: "белкIес",
    english: "to write",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/swim.webp"),
    category: "verbs",
    russian: "плавать",
    khadar: "юздуукIас",
    english: "to swim",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/cry.webp"),
    category: "verbs",
    russian: "плакать",
    khadar: "исес",
    english: "to cry",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/cover.webp"),
    category: "verbs",
    russian: "покрыть",
    khadar: "къаппарес",
    english: "to cover",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/bring.webp"),
    category: "verbs",
    russian: "приносить",
    khadar: "гатес",
    english: "to bring",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/wake_up.webp"),
    category: "verbs",
    russian: "проснуться",
    khadar: "тIатIугьес",
    english: "to wake up",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/repeat.webp"),
    category: "verbs",
    russian: "повторить",
    khadar: "тикрарбарес",
    english: "to repeat",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/bow.webp"),
    category: "verbs",
    russian: "поклоняться",
    khadar: "суждабарес",
    english: "to bow",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/put.webp"),
    category: "verbs",
    russian: "положить",
    khadar: "буцес",
    english: "to put",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/accept.webp"),
    category: "verbs",
    russian: "принять",
    khadar: "кьабулбарес",
    english: "to accept",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/say.webp"),
    category: "verbs",
    russian: "сказать",
    khadar: "эс",
    english: "to say",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/look.webp"),
    category: "verbs",
    russian: "смотреть",
    khadar: "тIарукIас",
    english: "to look",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/eat.webp"),
    category: "verbs",
    russian: "есть",
    khadar: "букес",
    english: "to eat",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/increase.webp"),
    category: "verbs",
    russian: "увеличить",
    khadar: "дакъбарес",
    english: "to increase",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/decrease.webp"),
    category: "verbs",
    russian: "уменьшить",
    khadar: "камбарес",
    english: "to decrease",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/read.webp"),
    category: "verbs",
    russian: "читать",
    khadar: "бучIес",
    english: "to read",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: "",
    category: "verbs",
    russian: "являться, быть",
    khadar: "угьес",
    english: "to be",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/run.webp"),
    category: "verbs",
    russian: "бежать",
    khadar: "дуцукIас",
    english: "to run",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/fall.webp"),
    category: "verbs",
    russian: "падать",
    khadar: "кайкес",
    english: "to fall",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/lay.webp"),
    category: "verbs",
    russian: "лежать",
    khadar: "кайхес",
    english: "to lay",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/stand.webp"),
    category: "verbs",
    russian: "стоять",
    khadar: "айтес",
    english: "to stand",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/mow.webp"),
    category: "verbs",
    russian: "косить",
    khadar: "ирщес",
    english: "to mow",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/find.webp"),
    category: "verbs",
    russian: "найти",
    khadar: "баргес",
    english: "to find",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/crawl.webp"),
    category: "verbs",
    russian: "ползать",
    khadar: "хусукIас",
    english: "to crawl",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/show.webp"),
    category: "verbs",
    russian: "показать",
    khadar: "къабакъес",
    english: "to show",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/be_hungry.webp"),
    category: "verbs",
    russian: "проголодаться",
    khadar: "гушуес",
    english: "to be hungry",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/cut.webp"),
    category: "verbs",
    russian: "резать",
    khadar: "балгъес",
    english: "to cut",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/turn_on.webp"),
    category: "verbs",
    russian: "включить",
    khadar: "бикьес",
    english: "to turn on",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/fly.webp"),
    category: "verbs",
    russian: "летать",
    khadar: "урцес",
    english: "to fly",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/jump.webp"),
    category: "verbs",
    russian: "прыгать",
    khadar: "парсукIас",
    english: "to jump",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/think.webp"),
    category: "verbs",
    russian: "думать",
    khadar: "пикриукIас",
    english: "to think",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    src: require("../../assets/verbs/rest.webp"),
    category: "verbs",
    russian: "отдыхать",
    khadar: "хIалукIас",
    english: "to rest",
    additional_info: "",
    sound_src: "apple.m4a",
  },
];
