export const adjectivesData = [
  {
    id: 1,
    src: require("../../assets/adjectives/poor.webp"),
    category: "Прилагательные",
    russian: "бедный",
    khadar: "гъариб",
    english: "poor",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 2,
    src: require("../../assets/adjectives/ill.webp"),
    category: "Прилагательные",
    russian: "больной",
    khadar: "изнаба",
    english: "ill",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 3,
    src: require("../../assets/adjectives/big.webp"),
    category: "Прилагательные",
    russian: "большой",
    khadar: "гьугил",
    english: "big",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 4,
    src: require("../../assets/adjectives/fast.webp"),
    category: "Прилагательные",
    russian: "быстрый",
    khadar: "гьалакъ",
    english: "fast",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 5,
    src: require("../../assets/adjectives/humid.webp"),
    category: "Прилагательные",
    russian: "влажный",
    khadar: "тимил",
    english: "humid",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 6,
    src: require("../../assets/adjectives/high.webp"),
    category: "Прилагательные",
    russian: "высокий",
    khadar: "укьенил",
    english: "high",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  //
  {
    id: 7,
    src: require("../../assets/adjectives/deep.webp"),
    category: "Прилагательные",
    russian: "глубокий",
    khadar: "мурхьил",
    english: "deep",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 8,
    src: require("../../assets/adjectives/deaf.webp"),
    category: "Прилагательные",
    russian: "глухой",
    khadar: "гIянца",
    english: "deaf",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 9,
    src: require("../../assets/adjectives/hot.webp"),
    category: "Прилагательные",
    russian: "горячий",
    khadar: "буцарил",
    english: "hot",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 10,
    src: require("../../assets/adjectives/loud.webp"),
    category: "Прилагательные",
    russian: "громкий",
    khadar: "цакьле",
    english: "loud",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 11,
    src: require("../../assets/adjectives/double.webp"),
    category: "Прилагательные",
    russian: "двойной",
    khadar: "кIудехIла",
    english: "double",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 12,
    src: require("../../assets/adjectives/expensive.webp"),
    category: "Прилагательные",
    russian: "дорогой",
    khadar: "багьай",
    english: "expensive",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 13,
    src: require("../../assets/adjectives/beautiful.webp"),
    category: "Прилагательные",
    russian: "красивый",
    khadar: "жагьой",
    english: "beautiful",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 14,
    src: require("../../assets/adjectives/robust.webp"),
    category: "Прилагательные",
    russian: "крепкий",
    khadar: "демъай",
    english: "robust",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 15,
    src: require("../../assets/adjectives/lightweight.webp"),
    category: "Прилагательные",
    russian: "легкий",
    khadar: "декьил",
    english: "light (weight)",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 16,
    src: require("../../assets/adjectives/favorite.webp"),
    category: "Прилагательные",
    russian: "любимый",
    khadar: "дигуй",
    english: "favorite",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 17,
    src: require("../../assets/adjectives/slow.webp"),
    category: "Прилагательные",
    russian: "медленный",
    khadar: "рахIатил",
    english: "slow",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 18,
    src: require("../../assets/adjectives/wet.webp"),
    category: "Прилагательные",
    russian: "мокрый",
    khadar: "шинил",
    english: "wet",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 20,
    src: require("../../assets/adjectives/young.webp"),
    category: "Прилагательные",
    russian: "молодой",
    khadar: "жагьил",
    english: "young",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 21,
    src: require("../../assets/adjectives/soft.webp"),
    category: "Прилагательные",
    russian: "мягкий",
    khadar: "кантIил",
    english: "soft",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 22,
    src: require("../../assets/adjectives/mute.webp"),
    category: "Прилагательные",
    russian: "немой",
    khadar: "гъайагьвара",
    english: "mute",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 23,
    src: require("../../assets/adjectives/low.webp"),
    category: "Прилагательные",
    russian: "низкий",
    khadar: "алашай",
    english: "low",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 24,
    src: require("../../assets/adjectives/new.webp"),
    category: "Прилагательные",
    russian: "новый",
    khadar: "сагай",
    english: "new",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 25,
    src: require("../../assets/adjectives/bad.webp"),
    category: "Прилагательные",
    russian: "плохой",
    khadar: "яман",
    english: "bad",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 26,
    src: require("../../assets/adjectives/next.webp"),
    category: "Прилагательные",
    russian: "следующий",
    khadar: "арагъакала",
    english: "next",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 27,
    src: require("../../assets/adjectives/previous.webp"),
    category: "Прилагательные",
    russian: "предыдущий",
    khadar: "гьадикала",
    english: "previous",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 28,
    src: require("../../assets/adjectives/visitor.webp"),
    category: "Прилагательные",
    russian: "приезжий",
    khadar: "дурашан",
    english: "visitor",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 29,
    src: require("../../assets/adjectives/light.webp"),
    category: "Прилагательные",
    russian: "светлый",
    khadar: "щаъил",
    english: "light (brightness)",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 30,
    src: require("../../assets/adjectives/free.webp"),
    category: "Прилагательные",
    russian: "свободный",
    khadar: "иркинле",
    english: "free",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 31,
    src: require("../../assets/adjectives/strong.webp"),
    category: "Прилагательные",
    russian: "сильный",
    khadar: "гучлу",
    english: "strong",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 32,
    src: require("../../assets/adjectives/sweet.webp"),
    category: "Прилагательные",
    russian: "сладкий",
    khadar: "миръил",
    english: "sweet",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 33,
    src: require("../../assets/adjectives/blind.webp"),
    category: "Прилагательные",
    russian: "слепой",
    khadar: "сукъур",
    english: "blind",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 34,
    src: require("../../assets/adjectives/middle.webp"),
    category: "Прилагательные",
    russian: "средний",
    khadar: "ургала",
    english: "middle",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 35,
    src: require("../../assets/adjectives/old.webp"),
    category: "Прилагательные",
    russian: "старый",
    khadar: "рухъна",
    english: "old",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 36,
    src: require("../../assets/adjectives/dry.webp"),
    category: "Прилагательные",
    russian: "сухой",
    khadar: "бугъуй",
    english: "old",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 37,
    src: require("../../assets/adjectives/solid.webp"),
    category: "Прилагательные",
    russian: "твердый",
    khadar: "чIачIе",
    english: "solid",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 38,
    src: require("../../assets/adjectives/quiet.webp"),
    category: "Прилагательные",
    russian: "тихий",
    khadar: "хархай",
    english: "quiet",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 39,
    src: require("../../assets/adjectives/heavy.webp"),
    category: "Прилагательные",
    russian: "тяжелый",
    khadar: "камхил",
    english: "heavy",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 40,
    src: require("../../assets/adjectives/dark.webp"),
    category: "Прилагательные",
    russian: "темный",
    khadar: "цIабил",
    english: "dark",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 41,
    src: require("../../assets/adjectives/cold.webp"),
    category: "Прилагательные",
    russian: "холодный",
    khadar: "даъил",
    english: "cold",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 42,
    src: require("../../assets/adjectives/white.webp"),
    category: "Прилагательные",
    russian: "белый",
    khadar: "цуба",
    english: "white",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 43,
    src: require("../../assets/adjectives/black.webp"),
    category: "Прилагательные",
    russian: "черный",
    khadar: "цудара",
    english: "black",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 44,
    src: require("../../assets/adjectives/fulvous.webp"),
    category: "Прилагательные",
    russian: "бурый",
    khadar: "къархIа",
    english: "fulvous",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 45,
    src: require("../../assets/adjectives/yellow.webp"),
    category: "Прилагательные",
    russian: "желтый",
    khadar: "букIута",
    english: "yellow",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 46,
    src: require("../../assets/adjectives/green.webp"),
    category: "Прилагательные",
    russian: "зеленый",
    khadar: "шиниша",
    english: "green",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 47,
    src: require("../../assets/adjectives/brown.webp"),
    category: "Прилагательные",
    russian: "коричневый",
    khadar: "нептIы",
    english: "brown",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 48,
    src: require("../../assets/adjectives/red.webp"),
    category: "Прилагательные",
    russian: "красный",
    khadar: "хIинтага",
    english: "red",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 49,
    src: require("../../assets/adjectives/sand.webp"),
    category: "Прилагательные",
    russian: "песочный",
    khadar: "гъаилатус",
    english: "sand",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 50,
    src: require("../../assets/adjectives/blue.webp"),
    category: "Прилагательные",
    russian: "синий",
    khadar: "ханца",
    english: "blue",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 51,
    src: require("../../assets/adjectives/color.webp"),
    category: "Прилагательные",
    russian: "цвет",
    khadar: "тус",
    english: "color",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 52,
    src: require("../../assets/adjectives/lightblue.webp"),
    category: "Прилагательные",
    russian: "голубой",
    khadar: "зубратус",
    english: "lightblue",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 53,
    src: require("../../assets/adjectives/small.webp"),
    category: "Прилагательные",
    russian: "маленький",
    khadar: "варгина",
    english: "small",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 54,
    src: require("../../assets/adjectives/cool.webp"),
    category: "Прилагательные",
    russian: "прохладный",
    khadar: "тахIауле",
    english: "cool",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 55,
    src: require("../../assets/adjectives/warm.webp"),
    category: "Прилагательные",
    russian: "теплый",
    khadar: "вагай",
    english: "warm",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 56,
    src: require("../../assets/adjectives/sharp.webp"),
    category: "Прилагательные",
    russian: "острый",
    khadar: "бугай",
    english: "sharp",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 57,
    src: require("../../assets/adjectives/sour.webp"),
    category: "Прилагательные",
    russian: "кислый",
    khadar: "цакIил",
    english: "sour",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 58,
    src: require("../../assets/adjectives/bitter.webp"),
    category: "Прилагательные",
    russian: "горький",
    khadar: "уткIуй",
    english: "bitter",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 59,
    src: require("../../assets/adjectives/spicy.webp"),
    category: "Прилагательные",
    russian: "перченый",
    khadar: "жангай",
    english: "spicy",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 60,
    src: require("../../assets/adjectives/thin.webp"),
    category: "Прилагательные",
    russian: "тонкий",
    khadar: "чукъай",
    english: "thin",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 61,
    src: require("../../assets/adjectives/fat.webp"),
    category: "Прилагательные",
    russian: "толстый",
    khadar: "церхил",
    english: "fat",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 61,
    src: require("../../assets/adjectives/shallow.webp"),
    category: "Прилагательные",
    russian: "мелкий, неглубокий",
    khadar: "сагIил",
    english: "shallow",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  
  
];
