export const pronounsData = [
  {
    id: 1,
    src: "",
    category: "Личные местоимения",
    russian: "я",
    khadar: "нуни",
    english: "I",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 2,
    src: "",
    category: "Личные местоимения",
    russian: "ты",
    khadar: "хIу",
    english: "you",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 3,
    src: "",
    category: "Личные местоимения",
    russian: "он, она, оно",
    khadar: "итI",
    english: "he, she, it",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 4,
    src: "",
    category: "Личные местоимения",
    russian: "мы",
    khadar: "нуша",
    english: "we",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 5,
    src: "",
    category: "Личные местоимения",
    russian: "вы",
    khadar: "хIуша",
    english: "you",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 6,
    src: "",
    category: "Личные местоимения",
    russian: "они",
    khadar: "итIи",
    english: "they",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 7,
    src: "",
    category: "Притяжательные местоимения",
    russian: "мой",
    khadar: "дия",
    english: "my",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 8,
    src: "",
    category: "Притяжательные местоимения",
    russian: "твой",
    khadar: "хIа",
    english: "your",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 9,
    src: "",
    category: "Притяжательные местоимения",
    russian: "итIия",
    khadar: "его, её",
    english: "his, her, its",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 10,
    src: "",
    category: "Притяжательные местоимения",
    russian: "наш",
    khadar: "нушия",
    english: "our",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 11,
    src: "",
    category: "Притяжательные местоимения",
    russian: "ваш",
    khadar: "хIушия",
    english: "your",
    additional_info: "",
    sound_src: "apple.m4a",
  },
  {
    id: 12,
    src: "",
    category: "Притяжательные местоимения",
    russian: "их",
    khadar: "итIила",
    english: "their",
    additional_info: "",
    sound_src: "apple.m4a",
  },

];
